chihaya:
  announce_interval: 15m
  prometheus_addr: localhost:6880
  max_numwant: 50
  default_numwant: 25

  http:
    addr: 0.0.0.0:6881
    allow_ip_spoofing: false
    real_ip_header: x-real-ip
    read_timeout: 5s
    write_timeout: 5s
    request_timeout: 5s

  udp:
    addr: 0.0.0.0:6881
    allow_ip_spoofing: false
    max_clock_skew: 10s
    private_key: |
      paste a random string here that will be used to hmac connection IDs

  storage:
    gc_interval: 14m
    peer_lifetime: 15m
    shards: 1

  prehooks:
  - name: infohash approval
    config:
      whitelist:
      - 0000000000000000000000000000000000000000
      blacklist:
      - 0000000000000000000000000000000000000000